# Generated by Django 5.0.2 on 2024-03-07 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_equipment_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='dateCompleted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('address', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenance',
            unique_together={('component', 'dateCompleted')},
        ),
    ]
