# Generated by Django 5.0.2 on 2024-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='component',
            field=models.CharField(max_length=150),
        ),
    ]
