# Generated by Django 5.0.2 on 2024-04-05 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_maintenance_maintenance_price_maintenance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
