# Generated by Django 5.0.2 on 2024-04-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_equipment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
